import { CallStatus, Category, Lead } from '../types/crm';

export const CALLERS = ['User 1', 'User 2'] as const;

export const CATEGORIES: Category[] = [
  'Doctor',
  'Dentist',
  'Physiotherapist',
  'Event Manager',
  'Event Planner',
  'Event Designer',
  'Anchor',
  'Decorator',
  'Other',
];

export const STATUS_CONFIG: Record<
  CallStatus,
  { label: CallStatus; color: string; bg: string; border: string }
> = {
  'Not Called': {
    label: 'Not Called',
    color: '#475569',
    bg: '#f1f5f9',
    border: '#cbd5e1',
  },
  'Interested': {
    label: 'Interested',
    color: '#059669',
    bg: '#ecfdf5',
    border: '#a7f3d0',
  },
  'Busy': {
    label: 'Busy',
    color: '#d97706',
    bg: '#fffbeb',
    border: '#fde68a',
  },
  'Wrong Number': {
    label: 'Wrong Number',
    color: '#9ca3af',
    bg: '#f3f4f6',
    border: '#e5e7eb',
  },
  'No Answer': {
    label: 'No Answer',
    color: '#64748b',
    bg: '#f8fafc',
    border: '#e2e8f0',
  },
  'Converted': {
    label: 'Converted',
    color: '#047857',
    bg: '#d1fae5',
    border: '#6ee7b7',
  },
  'Lost': {
    label: 'Lost',
    color: '#dc2626',
    bg: '#fef2f2',
    border: '#fecaca',
  },
};

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    business_name: 'Apex Dental Care & Implant Center',
    phone: '+919820112345',
    email: 'contact@apexdental.com',
    website: 'https://apexdental.example.com',
    maps_link: 'https://maps.google.com/?q=Apex+Dental+Care',
    review_count: 142,
    rating: 4.8,
    business_age: '5 Years',
    address: 'Bandra West, Mumbai',
    business_status: 'Operational',
    opening_hours: '9:00 AM - 8:00 PM',
    latest_review: 'Great service and very professional.',
    category: 'Dentist',
    city_area: 'Bandra West, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 1',
    status: 'Interested',
    priority: 'High',
    notes: 'Dr. Mehta expressed interest in lead management software. Wants a callback on Thursday.',
    follow_up_date: '2026-07-30',
    last_contact: '2026-07-28',
    remarks_preview: 'Positive response',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:10:00.000Z',
  },
  {
    id: 'lead-102',
    business_name: 'Grand Horizon Event Management',
    phone: '+919876543210',
    email: 'info@grandhorizonevents.in',
    website: 'https://grandhorizonevents.in',
    maps_link: 'https://maps.google.com/?q=Grand+Horizon+Events',
    review_count: 89,
    rating: 4.6,
    business_age: '12 Years',
    category: 'Event Manager',
    city_area: 'Andheri East, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 2',
    status: 'Interested',
    priority: 'High',
    notes: 'Spoke with CEO Rajesh. Demo scheduled for Friday 3 PM.',
    follow_up_date: '2026-07-31',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:15:00.000Z',
  },
  {
    id: 'lead-103',
    business_name: 'CureFit Physiotherapy Clinic',
    phone: '+919123456789',
    email: 'support@curefitphysio.com',
    website: '',
    maps_link: 'https://maps.google.com/?q=CureFit+Physio',
    review_count: 56,
    rating: 4.5,
    category: 'Physiotherapist',
    city_area: 'Juhu, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 1',
    status: 'Busy',
    priority: 'Medium',
    notes: 'Owner was busy with a patient. Asked to call back in the evening.',
    follow_up_date: '2026-07-28',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:05:00.000Z',
  },
  {
    id: 'lead-104',
    business_name: 'Royal Decorators & Stage Crafts',
    phone: '+919988776655',
    email: 'royaldecor.mumbai@gmail.com',
    website: 'https://royaldecor.com',
    maps_link: 'https://maps.google.com/?q=Royal+Decorators',
    review_count: 210,
    rating: 4.9,
    category: 'Decorator',
    city_area: 'Powai, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 2',
    status: 'Converted',
    priority: 'Low',
    notes: 'Closed client! Paid advance deposit for campaign package.',
    follow_up_date: '',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:20:00.000Z',
  },
  {
    id: 'lead-105',
    business_name: 'Starlight Emcee & Anchor Services',
    phone: '+919811223344',
    email: 'anchor.divya@example.com',
    website: '',
    maps_link: 'https://maps.google.com/?q=Starlight+Anchor',
    review_count: 34,
    rating: 4.7,
    category: 'Anchor',
    city_area: 'Lower Parel, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 1',
    status: 'Not Called',
    priority: 'None',
    notes: '',
    follow_up_date: '',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:00:00.000Z',
  },
  {
    id: 'lead-106',
    business_name: 'Vibrant Celebrations Event Planner',
    phone: '+919765432109',
    email: 'hello@vibrantcelebrations.in',
    website: 'https://vibrantcelebrations.in',
    maps_link: 'https://maps.google.com/?q=Vibrant+Celebrations',
    review_count: 175,
    rating: 4.8,
    category: 'Event Planner',
    city_area: 'Thane West',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 2',
    status: 'Lost',
    priority: 'None',
    notes: 'Already using a local software agency.',
    follow_up_date: '',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:18:00.000Z',
  },
  {
    id: 'lead-107',
    business_name: 'Skin Care & Dermatology Center',
    phone: '+919543210987',
    email: 'dr.sharma@skincareclinic.com',
    website: 'https://skincareclinic.com',
    maps_link: 'https://maps.google.com/?q=Skin+Care+Clinic',
    review_count: 312,
    rating: 4.9,
    category: 'Doctor',
    city_area: 'Worli, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 1',
    status: 'No Answer',
    priority: 'Medium',
    notes: 'Rang 5 times, no response. Will try again tomorrow.',
    follow_up_date: '2026-07-29',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:12:00.000Z',
  },
  {
    id: 'lead-108',
    business_name: 'Elegance Event Designers',
    phone: '+919432109876',
    email: 'contact@elegancedesigners.com',
    website: '',
    maps_link: 'https://maps.google.com/?q=Elegance+Event+Designers',
    review_count: 98,
    rating: 4.4,
    category: 'Event Designer',
    city_area: 'Malad West, Mumbai',
    batch_label: 'Batch 1 – 28 Jul 2026',
    assigned_to: 'User 2',
    status: 'Not Called',
    priority: 'None',
    notes: '',
    follow_up_date: '',
    created_at: '2026-07-28T02:00:00.000Z',
    updated_at: '2026-07-28T02:00:00.000Z',
  },
];
